# Generated by Django 5.1 on 2025-11-18 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=200, verbose_name="Ville")),
                ("radius_km", models.IntegerField(verbose_name="Rayon (km)")),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Appartement"),
                            ("house", "Maison"),
                            ("both", "Appartement et Maison"),
                        ],
                        default="both",
                        max_length=20,
                        verbose_name="Type de bien",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_zones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone de recherche",
                "verbose_name_plural": "Zones de recherche",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="ID externe"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("leboncoin", "Leboncoin"), ("seloger", "SeLoger")],
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL de l'annonce")),
                ("title", models.CharField(max_length=500, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Appartement"),
                            ("house", "Maison"),
                            ("both", "Appartement et Maison"),
                        ],
                        max_length=20,
                        verbose_name="Type de bien",
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix actuel"
                    ),
                ),
                (
                    "surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Surface (m²)",
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix au m²",
                    ),
                ),
                (
                    "rooms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nombre de pièces"
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nombre de chambres"
                    ),
                ),
                ("city", models.CharField(max_length=200, verbose_name="Ville")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Annonce active"),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Première détection"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière détection"
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de vente"
                    ),
                ),
                (
                    "has_price_changed",
                    models.BooleanField(default=False, verbose_name="Prix a changé"),
                ),
                (
                    "last_price_change_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date du dernier changement de prix",
                    ),
                ),
                (
                    "last_price_change_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Dernier % de changement",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="property_tracker.searchzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix"
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix au m²",
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% de changement",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Détecté le"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="property_tracker.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de prix",
                "verbose_name_plural": "Historiques de prix",
                "ordering": ["detected_at"],
                "indexes": [
                    models.Index(
                        fields=["listing", "detected_at"],
                        name="property_tr_listing_dc757d_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["external_id", "source"], name="property_tr_externa_90480d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["is_active"], name="property_tr_is_acti_3a1e23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["search_zone", "is_active"],
                name="property_tr_search__373fe7_idx",
            ),
        ),
    ]
