# Generated by Django 5.1 on 2025-11-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="source",
            field=models.CharField(
                choices=[("leboncoin", "Leboncoin")],
                max_length=20,
                verbose_name="Source",
            ),
        ),
    ]
