# Generated by Django 5.1 on 2025-11-18 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property_tracker", "0002_alter_listing_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSearchPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Paris", max_length=200, verbose_name="Ville"
                    ),
                ),
                (
                    "radius_km",
                    models.IntegerField(default=10, verbose_name="Rayon (km)"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Appartement"),
                            ("house", "Maison"),
                            ("both", "Appartement et Maison"),
                        ],
                        default="both",
                        max_length=20,
                        verbose_name="Type de bien",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférences de recherche",
                "verbose_name_plural": "Préférences de recherche",
            },
        ),
    ]
