# Generated by Django 5.1 on 2025-11-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tracker', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'image principale"),
        ),
    ]
