# Generated by Django 5.1 on 2025-11-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tracker', '0006_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchzone',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier scraping'),
        ),
        migrations.AddField(
            model_name='searchzone',
            name='last_successful_scrape_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier scraping réussi'),
        ),
    ]
