# Generated by Django 5.1 on 2025-12-01 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_tracker', '0007_add_scraping_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchzone',
            name='user',
        ),
        migrations.AddField(
            model_name='searchzone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zones', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AddField(
            model_name='usersearchpreferences',
            name='selected_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='property_tracker.searchzone', verbose_name='Zone sélectionnée'),
        ),
        migrations.AlterField(
            model_name='usersearchpreferences',
            name='city',
            field=models.CharField(blank=True, default='Paris', max_length=200, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='usersearchpreferences',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Appartement'), ('house', 'Maison'), ('both', 'Appartement et Maison')], default='both', max_length=20, verbose_name='Type de bien'),
        ),
        migrations.AlterField(
            model_name='usersearchpreferences',
            name='radius_km',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Rayon (km)'),
        ),
    ]
